- .travis.yml
- README.md
- ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/DateFormatter.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/utils/DateFormatter_Test.java
Enabling Travis CI for the sdk.  Fixed a timezone issue with the dateformatter so that the unit test will work regardless of what timezone you are in.
> Adding Travis CI Integration

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/BucketIntegration_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/DataIntegrity_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Insecure_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/NotificationsIntegration_test.java
- ds3-sdk-samples/src/main/java/com/spectralogic/ds3client/samples/BulkPutExample.java
- ds3-sdk-samples/src/main/java/com/spectralogic/ds3client/samples/Ds3BulkGetExample.java
- ds3-sdk-samples/src/main/java/com/spectralogic/ds3client/samples/Ds3ServiceListExample.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3Client.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3ClientImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/NetworkClientImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/AllocateJobChunkResponse.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/Ds3Request.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/GetAvailableJobChunksResponse.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/GetBucketResponse.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/HeadBucketResponse.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/ChunkTransferrer.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/ObjectPartTrackerImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/WriteJobImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/Checksum.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/ConnectionDetails.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/Headers.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/NetworkClient.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/WebResponse.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/MockNetwork.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/MockedHeaders.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/ObjectPartTrackerImpl_CompletePart_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/ObjectPart_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/utils/NetUtils_Test.java
This pull request has fixes for each of the following coverity bugs:
* 49088 - Resource Leak
* 49087 - Resource Leak on an Exception
* 49086 - Unguarded Read
Additionally this pull request has several non-functional code cleanup changes.
> Fixing Coverity Bugs and General Code Cleanup

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/BucketIntegration_Test.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3Client.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3ClientImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/GetObjectsRequest.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/GetObjectsResponse.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/S3Object.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/S3ObjectList.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/Ds3Client_Test.java
Test Results:
BUILD SUCCESSFUL
Total time: 24.74 secs
> Implemented get objects feature, complete with unit and integration tests

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/BucketIntegration_Test.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/ModifyJobRequest.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/bulk/Priority.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers_Test.java
Test Results:
BUILD SUCCESSFUL
Total time: 24.807 secs
> Added priority option to Modify Job, updated priority enum, deleted unused function

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/PutJobManagement_Test.java
Change response code check from 201 to 200 for initiate multipart upload.
> Change response code from 201 to 200 for initiate mulitpart upload

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/GetJobManagement_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/PutJobManagement_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/test/helpers/ABMTestHelper.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpersImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/options/ReadJobOptions.java
Adding get job tests, extracting wait for cache >0 function, and adding withName option to ReadJobOptions
> 3 2 autogen

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/UsersAndGroups_Test.java
The biggest risk for this file is leaving behind any created groups, group group members, user group members, bucket acls, or data policy acls.  I think I've got the try/catch/finally's set up to make sure this doesn't happen, but please be on the lookout for missed spots.  Cascading failures will occur if something doesn't get deleted properly.
> Complete Users, Groups, and Acls Integration Tests

- ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers_Test.java
Let's see if this resolves the failures.
> Separate stopwatch functions from assert functions

- contract/3_0_1_contract.xml
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/GetStorageDomainsSpectraS3Request.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/ModifyStorageDomainSpectraS3Request.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/PutStorageDomainSpectraS3Request.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/BulkObject.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/DataIsolationLevel.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/ImportConflictResolutionMode.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/MasterObjectList.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/StorageDomain.java
Reverts SpectraLogic/ds3_java_sdk#276
> Revert "Updated to from 3.0.1 to 3.0.2 API"

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Smoke_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/test/helpers/ABMTestHelper.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/test/helpers/JobStatusHelper.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/test/helpers/TempStorageIds.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/test/helpers/TempStorageUtil.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpersImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/FolderNameFilter.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/EmptySeekableByteChannel.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/Predicate.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/FolderNameFilter_Test.java
Add retry helper for expected JobStatus
Merge commit #291 from master: Creating a map and filter that will take a list of Contents, Filter them, and then convert them to Ds3Objects to ease development effort, and support filtering of unwanted files.
> Add retries for expected job status

- ds3-sdk/src/main/java/com/spectralogic/ds3client/ConnectionDetailsImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3ClientBuilder.java
Cherry-picked commit from 3.0 version of SDK
> Clarify units in client building

- ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/NetworkClientImpl.java
Not cherry-picked due to merge conflict when attempting to grab from master branch (3.0)
> Improved network client logging to include server request id

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/test/helpers/ABMTestHelper.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/test/helpers/TempStorageUtil.java
to facilitate clean up after failed tests
> (JSDK136) Remove all buckets with data policy

- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpersImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/ObjectPartTrackerImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/ReadJobImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/WaitingForChunksListener.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/WriteJobImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/events/ConcurrentEventRunner.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/events/EventRunner.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/events/Events.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/SingleThreadedEventRunner.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/JobPartTrackerFactory_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/ObjectPartTrackerImpl_CompletePart_Test.java
Modified the event handlers so that they emit all their events in an Event class which will asynchronously run the events.  Also added a new event to notify a user when the client has to wait for more chunks.  And made the polling interval between checking for available chunks configurable.
> Events Updates

- docker/docker-compose.yml
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpersImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/FileObjectPutter.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/ObjectChannelBuilderLogger.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/ReadJobImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/events/ConcurrentEventRunner.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/events/SameThreadEventRunner.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/SafeStringManipulation.java
This includes removing some unused imports, adding more documentation, and a fix for a race condition introduced with the async event runners.
> Code cleanup and docs

- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpersImpl.java
> Renaming a variable to better reflect what it is.

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/helpers/channelbuilders/ObjectStreamBuilder_Test.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/channelbuilders/ObjectInputStreamBuilder.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/channelbuilders/ObjectOutputStreamBuilder.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/channelbuilders/ReadOnlySeekableByteChannel.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/channelbuilders/WriteOnlySeekableByteChannel.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/NotImplementedException.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/channelbuilders/ObjectInputStreamBuilder_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/channelbuilders/ObjectOutputStreamBuilder_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/channelbuilders/StreamObjectGetter.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/channelbuilders/StreamObjectPutter.java
**Tests**
Added unit and integration tests to verify that that data is properly transferred using streams
> JSDK 146 - added overload to the transfer method for an OutputStream/InputStream builder

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Metadata_Test.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/interfaces/AbstractRequest.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/interfaces/MetadataImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/interfaces/RequestHeaders.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/interfaces/RequestHeadersImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/NetworkClientImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/MetadataStringManipulation.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/commands/interfaces/RequestHeadersImpl_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/utils/MetadataStringManipulation_Test.java
**Changes**
- Created request header wrapper that percent encodes metadata
- Added percent decoding to response HeadersImpl
- Added metadata encoding integration tests
> Percent encode metadata

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Metadata_Test.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/interfaces/AbstractRequest.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/interfaces/MetadataImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/interfaces/RequestHeaders.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/interfaces/RequestHeadersImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/NetworkClientImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/MetadataStringManipulation.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/commands/interfaces/RequestHeadersImpl_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/utils/MetadataStringManipulation_Test.java
All tests passed.
Same commits that were merged into master in the following pull requests:
https://github.com/SpectraLogic/ds3_java_sdk/pull/401
https://github.com/SpectraLogic/ds3_java_sdk/pull/406
> Percent encoded metadata

- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/RangeHelper.java
to get an immutable list.  Just create the immutable list directly.
> Had been making an unnecessary copy of a mutable list

- ds3-sdk-samples/src/main/java/com/spectralogic/ds3client/samples/PutEmptyFolderExample.java
JAVASDK-190: Create code sample showing how to create directory using Standard S3
> JSDK-190 merge with master

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Smoke_Test.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpersImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/JobRecoveryException.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/JobRecoveryNotActiveException.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/JobRecoveryTypeException.java
Same code that was merged to master in pr https://github.com/SpectraLogic/ds3_java_sdk/pull/421
> JSDK-192 (3.4 branch): Explicit check for active job before recovering job in helpers

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Metadata_Test.java
- ds3-sdk-samples/src/main/java/com/spectralogic/ds3client/samples/BulkPutWithMetadata.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/PutObjectRequest.java
Fix for https://jira.spectralogic.com/browse/JSDK-215
> Fixing a bug where we were passing along uppercase keys in user-defined metadata

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/helpers/FileSystemHelper_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/GetJobManagement_Test.java
Removing dependency on java's file modifications, as they have proven unreliable.
> Docker file permissions broken

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/helpers/FileSystemHelper_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/GetJobManagement_Test.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/FileSystemHelper.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/FileSystemHelperImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/ObjectStorageSpaceVerificationResult.java
The version of java on the docker container does not correctly report file permissions.
> Fix for one of the failing integration tests

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/PutJobManagement_Test.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/ConnectionDetailsImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3ClientBuilder.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/ConnectionDetails.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/NetworkClientImpl.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/Ds3Client_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/utils/NetUtils_Test.java
Adding ability to specify user agent in client builder.
> Fix for https://jira.spectralogic.com/browse/JSDK-221

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Smoke_Test.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/interfaces/AbstractRequest.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/SafeStringManipulation.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/utils/SafeString_Manipulation_Test.java
Created safe percent encoding function for query parameters.
> BPBROWSER 93- Percent encoding query parameters

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Smoke_Test.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/interfaces/AbstractRequest.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/SafeStringManipulation.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/utils/SafeString_Manipulation_Test.java
Separated percent encoding for url and query params
> Update query param escaping

- contract/4_0_0_contract.xml
**Changes**
- Updating contract that was used to generate commands from 3.4.1 to 4.0.0
> Updated contract used to generate 4.0.0 api

- build.gradle
- ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/PropertyUtils.java
Not exactly sure why we got the NPE, as extracting the files after pulling down the 'all' jar shows the .properties file where we expect it with the right contents, so...
> Fix for https://jira.spectralogic.com/browse/JSDK-245 Null Pointer exception for get system info.

- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/pagination/GetBucketKeyLoaderFactory.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/pagination/GetBucketLoaderFactory.java
This is a small pull request to restore the method signature that had been overlooked in my previous pull request.
> JSDK-247 - Ensuring method signature compatability

- ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/NetworkClientImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/DateFormatter.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/utils/DateFormatter_Test.java
for compatibility with English BP server
Also fix a few typos 882 -> 822
> Force US locale in Ds3Request Date header

- build.gradle
- ds3-sdk/build.gradle
- ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/PropertyUtils.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/Ds3Client_Test.java
Putting git commit hash into ds3-sdk.properties file.
> Fix for https://jira.spectralogic.com/browse/JSDK-268.

- build.gradle
- docker/run_docker.rb
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/UsersAndGroups_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/test/helpers/TempStorageUtil.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3Client.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3ClientImpl.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/DelegateCreateUserSpectraS3Request.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/GetDataPoliciesSpectraS3Request.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/ModifyDataPolicySpectraS3Request.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/ModifyUserSpectraS3Request.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/PutDataPolicySpectraS3Request.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/UndeleteObjectSpectraS3Request.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/UndeleteObjectSpectraS3Response.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/Bucket.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/BulkObject.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/DataPolicy.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/JobChunk.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/S3Object.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/SpectraUser.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/VersioningLevel.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/Ds3Client_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers_Test.java
Added minimal support needed to enable DS3 replication against the 5.0.0 release API.
> V3 2 8 5 0 merge

- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/bulk/Ds3Object.java
This can cause a null pointer.
> This prevents a null pointer in the case where the versionId is null

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Metadata_Test.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/interfaces/RequestHeadersImpl.java
- ds3-utils/src/main/java/com/spectralogic/ds3client/commands/interfaces/MetadataImpl.java
- ds3-utils/src/main/java/com/spectralogic/ds3client/utils/MetadataStringManipulation.java
- ds3-utils/src/test/java/com/spectralogic/ds3client/utils/MetadataStringManipulation_Test.java
once this PR is approved and merge I can cherry-pick it to master
> Fix metadata header escape, split between key and value

- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Metadata_Test.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/interfaces/RequestHeadersImpl.java
- ds3-utils/src/main/java/com/spectralogic/ds3client/commands/interfaces/MetadataImpl.java
- ds3-utils/src/main/java/com/spectralogic/ds3client/utils/MetadataStringManipulation.java
- ds3-utils/src/test/java/com/spectralogic/ds3client/utils/MetadataStringManipulation_Test.java
cherry-pick commit 5222654f4a67de9ffa07e3284a1901d4365678c4 from v_3_5_5
PR https://github.com/SpectraLogic/ds3_java_sdk/pull/567
> (1) Cherry-pick: Fix metadata header escape, split between key and value

- ds3-metadata/src/test/java/com/spectralogic/ds3client/metadata/MACMetadataRestore_Test.java
- ds3-metadata/src/test/java/com/spectralogic/ds3client/metadata/PosixMetadataRestore_Test.java
- ds3-metadata/src/test/java/com/spectralogic/ds3client/metadata/PosixMetadataStore_Test.java
- ds3-metadata/src/test/java/com/spectralogic/ds3client/metadata/WindowsMetadataRestore_Test.java
- ds3-metadata/src/test/java/com/spectralogic/ds3client/metadata/WindowsMetadataStore_Test.java
- ds3-sdk-integration/src/main/java/com/spectralogic/ds3client/integration/Util.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/helpers/channelbuilders/ObjectStreamBuilder_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/AdvancedBucketManagement_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/CustomParser_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/GroupManagement_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Regression_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Smoke_Test.java
- ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/UsersAndGroups_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/Ds3Client_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/commands/interfaces/RequestHeadersImpl_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/commands/parsers/utils/ResponseParserUtils_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/commands/spectrads3/GetPutJobToReplicate_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/JobPartTracker_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/models/ModelFunctionality_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/models/ModelParsing_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/models/ServiceList_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/networking/FailedRequestException_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/utils/SafeString_Manipulation_Test.java
- ds3-utils/src/test/java/com/spectralogic/ds3client/utils/MetadataStringManipulation_Test.java
cherry-pick commit 827d6660efb93345e05883816aeef1d734bc94a7 from v_3_5_5
PR https://github.com/SpectraLogic/ds3_java_sdk/pull/568
* This should be merged after https://github.com/SpectraLogic/ds3_java_sdk/pull/570
> (2) Cherry-pick: Fix 'Method names should not contain underscores' issue

- ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/FileObjectGetter.java
(#566)
* This still needs testing but this is the sparse fix
* using slices
* removing extra get for slice
> Cherrypick of sparefile to 3.5.5 (#566)

- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/HeadObjectResponse.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/parsers/HeadObjectResponseParser.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/parsers/utils/ResponseParserUtils.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/Ds3Client_Test.java
- ds3-sdk/src/test/java/com/spectralogic/ds3client/commands/parsers/utils/ResponseParserUtils_Test.java
Adding in parsing for new headers 'creation-date' and 'version-id' into the head object response payload.
> JSDK-297: Add new Header value to HEAD Object.

- ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/NetworkClientImpl.java
> Cherrypick of PR #582

- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/Error.java
Nothing else changes with this fix.
> Add Serializable to Error

- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/Error.java
> Add Serializable to Error - cherry-pick

- build.gradle
- ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/DeleteObjectsRequest.java
- ds3-sdk/src/main/java/com/spectralogic/ds3client/models/delete/DeleteObject.java
Updating DeleteObjectsRequest to allow the specification of object version ID so that client's can specify a version to be deleted.
> Fix delete objects request payload

- .github/workflows/tests.yml
For now, this is in addition to travisCI.
> Use github actions for testing

- .github/workflows/tests.yml
- ds3-sdk-integration/build.gradle.kts
Test PRs to ensure integration tests compile successfully.
> Fix integration test compilation

- buildSrc/src/main/kotlin/ds3-java-sdk-publishing-common-convention.gradle.kts
- ds3-bom/build.gradle.kts
- ds3-interfaces/build.gradle.kts
- ds3-metadata/build.gradle.kts
- ds3-sdk/build.gradle.kts
- ds3-utils/build.gradle.kts
Also, ensure the description is included in the generated maven pom.
> Add descriptions to published gradle subprojects
