ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/BucketIntegration_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/DataIntegrity_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/NotificationsIntegration_test.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3Client.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3ClientImpl.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/NetworkClientImpl.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/DeleteMultipleObjectsRequest.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/DeleteMultipleObjectsResponse.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/models/delete/Delete.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/models/delete/DeleteObject.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/models/delete/DeleteResult.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/models/delete/Deleted.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/models/delete/Error.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/NetUtils.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/Ds3Client_Test.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/MockNetwork.java
This pull request adds support for the S3 Multi Object Delete API call.  Additionally there is a minor documentation improvement calling out that the Job transfer method is a blocking call.
=> MultiObject Delete Support w/Minor Documentation Addition

build.gradle, ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3Client.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3ClientImpl.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/DeleteTapeDriveRequest.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/DeleteTapeDriveResponse.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/DeleteTapePartitionRequest.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/DeleteTapePartitionResponse.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/GetAvailableJobChunksRequest.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/Ds3Client_Test.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/utils/NetUtils_Test.java
This pull request adds support for DeleteTapeDrive and DeleteTapePartition.  Additionally this call added the `preferred_number_of_chunks` query param to the `GetAvailableJobChunksRequest`
=> Delete Tape Drive and Partition Call Support

ds3-sdk/build.gradle, ds3-sdk/src/main/java/com/spectralogic/ds3client/serializer/XmlOutput.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/serializer/XmlOutput_Test.java
denverm@dm-lt:~/code/github/ds3_java_sdk$ ./gradlew clean test
:ds3-sdk:clean
:ds3-sdk-integration:clean
:ds3-sdk-samples:clean UP-TO-DATE
:ds3-sdk:compileJava
:ds3-sdk:processResources UP-TO-DATE
:ds3-sdk:classes
:ds3-sdk:compileTestJava
:ds3-sdk:processTestResources
:ds3-sdk:testClasses
:ds3-sdk:test
:ds3-sdk:genConfigProperties
:ds3-sdk:jar
:ds3-sdk-integration:compileJava
:ds3-sdk-integration:processResources UP-TO-DATE
:ds3-sdk-integration:classes
:ds3-sdk-integration:compileTestJava
:ds3-sdk-integration:processTestResources
:ds3-sdk-integration:testClasses
:ds3-sdk-integration:test
:ds3-sdk-samples:compileJava
:ds3-sdk-samples:processResources UP-TO-DATE
:ds3-sdk-samples:classes
:ds3-sdk-samples:compileTestJava UP-TO-DATE
:ds3-sdk-samples:processTestResources UP-TO-DATE …
=> JSDK: Add a Build Time Flag to disable XML Validation

ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/AdvancedBucketManagement_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/DataIntegrity_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/GroupManagement_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Metadata_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/NotificationsIntegration_test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/PutJobManagement_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Regression_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Smoke_Test.java
This fixes the nightly test failures - is not encountered on sm25-2 in live testing because the default data-policy is used
Also optimize test imports.
=> Update tests to not require End-to-end-crc on test bucket.

ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpersImpl.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/options/WriteJobOptions.java
Add to WriteJobOptions and pass to request through helper.
=> Javacli-98 expose ignoreNamingConflicts option through helper 

docker/docker-compose.yml, docker/run_tests.sh, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/PutJobManagement_Test.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpersImpl.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/ExceptionClassifier.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/JobPartTrackerImpl.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/JobState.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/WriteJobImpl.java
This adds a decorator to WriteJobImpl.transfer to enable retrying failed object puts. The PutJobManagement_Test class has a testWriteJobWithRetries that will fail once with a mocked Ds3ClientImpl and may fail again if you point the integration test at an http proxy that can inject errors. See https://github.com/GraciesPadre/test-proxy. Setting the environment variable DS3_ENDPOINT to something like http://192.168.6.156:9080 (a docker container running the http proxy) will cause the test to test to fail a second time due to the proxy failing the put object request the first time it's seen. It is not necessary to run the http proxy if you don't want to; the integration test will verify retry behavior by using the mocked Ds3ClientImpl.
=> Put object retries

docker/run_tests.sh
Taking the shutdown out prevents the docker shell from reporting an error.
=> No longer need to shut the http proxy down from the run-tests script, because the jenkins job does so.

ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/WriteJobImpl.java
when removing a misguided attempt to take a job out of running state.
=> Missed one spot 

ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/parsers/utils/ResponseParserUtils.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/FailedRequestException.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/FailedRequestUsingMgmtPortException.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/networking/HeadersImpl.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/commands/parsers/utils/ResponseParserUtils_Test.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers_Test.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/networking/FailedRequestException_Test.java
**Changes**
- Retrieves request-id from response headers in failing request exception
- Adds request-id to exception message
- Created unit tests for new util function `getRequestId` that retrieves the `x-amz-request-id` from the web response headers
=> Added request id to failed request exception

ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Regression_Test.java
**Change**
The merge of `master` with `3_2_2_autogen` left a reference to `getStatusCode`, which now causes a compilation error.  Therefore, this line was removed from the test.
=> Removed old reference to getStatusCode

ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/PutJobManagement_Test.java
An integration test broke when I introduced a change into the http proxy, where I injected a fault into the file lesmis-copies.txt.  Using a different file in this test is still valid, because we're using a ds3 client shim that also injects faults, which exercises the logic we're trying to validate with
this test -- retry logic.  I'll update this test when I get finished with the partial read retry stuff I'm working on, which is why I monkeyed with
the http proxy to begin with :(
=> Fix integration tests that broke with latest http proxy

ds3-sdk-integration/build.gradle, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/helpers/FileSystemHelper_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/GetJobManagement_Test.java
that set directory permissions for the evil that is Redmond.
=> Fixing integration tests 

ds3-sdk/src/test/java/com/spectralogic/ds3client/utils/MetadataStringManipulation_Test.java
Unit tests failed to compile in docker due to unknown symbols. Updated symbols to Unicode format.
=> Updated greek symbols to unicode representation in unit test

ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Smoke_Test.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpersImpl.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/JobRecoveryException.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/JobRecoveryNotActiveException.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/JobRecoveryTypeException.java
**Changes**
- Added verification that job is active before performing job recovery in helpers
- Modified `JobRecoveryException` so helper function signatures will not change
- created `JobRecoveryTypeException` which extends `JobRecoverException` to specify failure due to type. This contains the behavior that was previously within `JobRecoveryException`
- created `JobRecoveryNotActiveException` to specify failure related to the job not being active
- Added additional integration tests for both `recoverReadJob` and `recoverWriteJob` to verify canceled and non-existent jobs throw the new `JobRecoveryNotActiveException`
=> Explicit check for active job before recovering job in helpers

README.md, docker/README.md
Fix incorrect text for a referenced URL (which was correct) in top level README.md
=> Fix copy-n-paste typo in docker README.md

docker/run_tests.sh
denverm@dm-lt:~/code/ds3_java_sdk/docker$ ./run_tests.sh 
Using Git Repo: https://github.com/SpectraLogic/ds3_java_sdk.git
Using Git Branch: master
DS3_ENDPOINT sm2u-11.eng.sldomain.com
DS3_SECRET_KEY sKkCwmVf
DS3_ACCESS_KEY c3BlY3RyYQ==
+ cd /opt
+ '[' master '!=' master ']'
+ git clone https://github.com/SpectraLogic/ds3_java_sdk.git
Cloning into 'ds3_java_sdk'...
remote: Counting objects: 42399, done.
remote: Compressing objects: 100% (1818/1818), done.
remote: Total 42399 (delta 1636), reused 0 (delta 0), pack-reused 40491
Receiving objects: 100% (42399/42399), 21.17 MiB | 8.20 MiB/s, done.
Resolving deltas: 100% (30712/30712), done.
Checking connectivity... done.
+ cd ds3_java_sdk
+ git rev-parse HEAD
ff0e265937f24da49d00376cdd639e02ae5205d6
+ ./gradlew jar …
=> Print the git HEAD rev hash before running tests

ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/GetJobManagement_Test.java
Since there are other tests that exercise the ability to detect an error, not running this particular one as root is not a concern.
=> Fixing a test that really does not make sense to run as root.

ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Iterators_Test.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/DeleteDataPersistenceRuleSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/GetDataPersistenceRuleSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/ModifyDataPersistenceRuleSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/RawImportAllTapesSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/RawImportTapeSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/exceptions/UnableToConvertToCommonPrefixesException.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/exceptions/UnableToConvertToContentsException.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpersImpl.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/pagination/FileSystemKey.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/pagination/GetBucketKeyLoaderFactory.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/models/ActiveJob.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/models/TapeDrive.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers_Test.java
**Changes**
- Moved some pagination files from `models` folder into `helpers` and `exceptions` folder
- Generated 3.5 api
=> Update to 3 5 api

ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/UsersAndGroups_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/test/helpers/TempStorageUtil.java
**Changes**
- Created static string for default user name. Replaced all references to "spectra" with default user variable.
- Updated default user from "spectra" to "Administrator" for 4.0 compatibility.
=> Updated default user to Adiministrator in integration tests

ds3-sdk-integration/src/main/java/com/spectralogic/ds3client/integration/Util.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Smoke_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/UsersAndGroups_Test.java
**Changes**
-Updating `GetObjects` test with the 4.0 update of paging always enabled
- Created `assumeVersion3orLess` to temporarily not run tests in 4.0 that are failing due to changes in API.  Now the BP throws errors when we pass in a random UUID for page-start-marker optional parameter. The error is currently a 410, but will be updated to 400 or 404 shortly.  Will update tests when BP handling of this scenario is decided and updated.
=> Updating broken tests due to 4.0 API changes

ds3-sdk-integration/src/main/java/com/spectralogic/ds3client/integration/Util.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/UsersAndGroups_Test.java
**Changes**
Updated tests in `UsersAndGroups_Test` to reflect change from 3.5 -> 4.0 where creating a command with optional `PageStartMarker` pointing to a non-existent UUID now returns a 404 (where previously it did not error).
=> Updated tests in UsersAndGroups to reflect change in 4.0.0 api

ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/helpers/FileSystemHelper_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Smoke_Test.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3Client.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3ClientImpl.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/decorators/PutFolderRequest.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/decorators/PutFolderResponse.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/exceptions/FolderNameMissingTrailingForwardSlash.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpersImpl.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/Ds3Client_Test.java
**Changes**
- `PutFolder` command added as wrapper to put object. Throws error if the folder name is not valid, i.e. does not end with `/`
- Created helper function which combines put bulk job and put folder command, ensuring correct folder creation.
=> JSDK-242: Created Put Folder command which wraps the Put Object command

ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/helpers/FileSystemHelper_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Smoke_Test.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3Client.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3ClientImpl.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/decorators/PutFolderRequest.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/decorators/PutFolderResponse.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/exceptions/FolderNameMissingTrailingForwardSlash.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpersImpl.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/Ds3Client_Test.java
Same content that was merged to master in PR https://github.com/SpectraLogic/ds3_java_sdk/pull/483
=> JSDK 242 fix for 4.0 branch

ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3Client.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/interfaces/AbstractIdsPayloadRequest.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/ClearSuspectBlobAzureTargetsSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/ClearSuspectBlobPoolsSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/ClearSuspectBlobS3TargetsSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/ClearSuspectBlobTapesSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/GetPoolsSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/MarkSuspectBlobAzureTargetsAsDegradedSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/MarkSuspectBlobDs3TargetsAsDegradedSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/MarkSuspectBlobPoolsAsDegradedSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/MarkSuspectBlobS3TargetsAsDegradedSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/MarkSuspectBlobTapesAsDegradedSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/models/TapeDriveType.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/models/requestpayloads/Ids.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/Ds3Client_Test.java
**Changes**
- Added new abstract class which handles creation of stream payload of ids from list of ids `AbstractIdsPayloadRequest`
- Updated 9 commands to use new request payload types
- Added unit test to verify new request payload is marshaled as expected
- Re-generated SDK with newest 4.0.0 API which has minor changes not related to SA-193
=> SA-193: Fixed request payloads with IDs payload

ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/PropertyUtils.java
Not exactly sure why we got the NPE, as extracting the files after pulling down the 'all' jar shows the .properties file where we expect it with the right contents, so...
=> Fix for https://jira.spectralogic.com/browse/JSDK-245 Null Pointer exception for get system info

.gitignore, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/FileObjectGetter.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/helpers/FileObjectGetter_Test.java
Files.createDirectories fails with a FileAlreadyExists exception if there is a non-directory file in the provided path. This includes symbolic links. By including the FileUtils.resolveForSymbolic() we allow writing to paths that contain symbolic links.
=> JSDK-248 Correcting issue where FileObjectGetter does not respect symlinks

ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3Client.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/GetObjectRequest.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/PutMultiPartUploadPartRequest.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/PutObjectRequest.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/notifications/PutDs3TargetFailureNotificationRegistrationSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/notifications/PutJobCompletedNotificationRegistrationSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/notifications/PutJobCreatedNotificationRegistrationSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/notifications/PutJobCreationFailedNotificationRegistrationSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/notifications/PutObjectCachedNotificationRegistrationSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/notifications/PutObjectLostNotificationRegistrationSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/notifications/PutObjectPersistedNotificationRegistrationSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/notifications/PutPoolFailureNotificationRegistrationSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/notifications/PutStorageDomainFailureNotificationRegistrationSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/notifications/PutSystemFailureNotificationRegistrationSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/notifications/PutTapeFailureNotificationRegistrationSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/notifications/PutTapePartitionFailureNotificationRegistrationSpectraS3Request.java
**Changes**
- Added `Nonnull` annotation to channel and stream parameters to request handler constructors.
- Added precondition to verify channels and streams are non-null in request handler constructors.
=> SA-210: Ensuring streams and channels are not null

ds3-sdk/src/test/java/com/spectralogic/ds3client/Ds3Client_Test.java
All constructors with stream or channel inputs now have a negative test to verify preconditions are working as expected. This consists of all constructors for:
- GetObjectRequest
- PutObjectRequest
- PutMultiPartUploadPartRequest
Note: each tests is catching two exceptions. The null pointer exception is thrown by the precondition in the constructor (expected), and the illegal argument exception is thrown in IntelliJ IDEA due to the Nonnull annotation.
=> JSDK-257: Negative tests for null streams and channels

contract/4_0_0_contract.xml
The BP contract located within the contract folder was outdated. This specifies the contract used to generate the commands.
=> Updating stale contract used for generation

README.md, SETUP.md, build.gradle, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/helpers/FileSystemHelper_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/GetJobManagement_Test.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/PutJobManagement_Test.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/exceptions/ContentLengthNotMatchException.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/Ds3ClientHelpers.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/strategy/channelstrategy/SeekableByteChannelDecorator.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/strategy/channelstrategy/SequentialChannelStrategy.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/strategy/transferstrategy/GetJobNetworkFailureRetryDecorator.java
Merging fix for sequential blobbed file transfer from master to 3.5.3.
Merging fix for creating ranged gets from network retries into 3.5.3
=> Merging into v3_5_3

ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/ExceptionClassifier.java
Seems that building on a machine that has both java 8 & 9 JDKs using the java 8 javac causes java 9
jars to get pulled in.
=> Fix for https://jira.spectralogic.com/browse/BPBROWSER-408

contract/5_0_x_contract.xml, ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3Client.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3ClientImpl.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/parsers/UndeleteObjectSpectraS3ResponseParser.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/UndeleteObjectSpectraS3Request.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/spectrads3/UndeleteObjectSpectraS3Response.java
=> Adding undelete object command

build.gradle, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/DeleteObjectsRequest.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/models/DeleteObjectError.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/models/delete/DeleteObject.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/Ds3Client_Test.java
Add versionId to DeleteObject, DeleteObjectsRequest and DeleteObjectError.
=> Version id in payload

ds3-sdk-integration/src/main/java/com/spectralogic/ds3client/integration/Util.java, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/VersionedObject_Test.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/strategy/transferstrategy/GetJobPartialBlobTransferMethod.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/strategy/transferstrategy/GetJobTransferMethod.java
- Added version ID to helper get job transfer methods
- Added util in test for deleting all buckets and their contents because I didn't want to manually delete 100+ buckets manually when the cascade failure happened due to BP bug.
=> JSDK-285: Updating get job transfer methods to add version id when getting object

ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/FileObjectGetter.java
I'm not sure how to write a unit test for this issue, but after working a lot with Kyle I believe this is a fix.
=> This still needs testing but this is the sparse fix

ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/PutJobManagement_Test.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/Ds3InputStreamEntity.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/PutMultiPartUploadPartRequest.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/channelbuilders/ReadOnlySeekableByteChannel.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/strategy/channelstrategy/SeekableByteChannelDecorator.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/strategy/channelstrategy/SequentialChannelStrategy.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/helpers/strategy/transferstrategy/TransferStrategyBuilder.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/ReadOnlySeekableByteChannelInputStream.kt, ds3-sdk/src/main/java/com/spectralogic/ds3client/utils/SeekableByteChannelInputStream.java
This is a bit of a hack, but it passes all the tests now.
=> Streaming Fix - JSDK-298

build.gradle, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/HeadObjectResponse.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/parsers/HeadObjectResponseParser.java, ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/parsers/utils/ResponseParserUtils.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/Ds3Client_Test.java, ds3-sdk/src/test/java/com/spectralogic/ds3client/commands/parsers/utils/ResponseParserUtils_Test.java
Merging some fixes from both v5.1.2 and v5.0.6
Also reving version to v5.1.3
=> Merging missing fixes

.travis.yml, build.gradle, ds3-sdk-integration/src/test/java/com/spectralogic/ds3client/integration/Smoke_Test.java, gradle/wrapper/gradle-wrapper.properties
- Updating build to use Java 8 for improvements in SSL library
- Updating to Gradle 4.6
- Also fixed some non-compiling tests
- Reeving version to COMPAT-5
=> JSDK-109: Improve SSL GCM performance

.github/workflows/tests.yml, buildSrc/src/main/kotlin/ds3-java-sdk-internal-convention.gradle.kts, buildSrc/src/main/kotlin/ds3-java-sdk-library-convention.gradle.kts
Update GitHub actions to use all LTS versions of Java for testing (currently 8,
11, and 17), and make sure gradle is configured to produce Java 8 bytecode no
matter what JDK is used.
=> Test all Java LTS versions

buildSrc/src/main/kotlin/ds3-java-sdk-library-convention.gradle.kts
In addition to allow us to publish to our own local maven repository, this will allow jitpack to create artifacts for us to use.
=> Enable local publishing

docker/run_tests.sh
In addition to the unit tests, make sure to run the integration tests when running the test suite in docker.
=> Run integrationTest task in docker

README.md, libs.versions.toml
Begin to use SNAPSHOT version between releases.
=> Update README and move to 5.6.1-SNAPSHOT

.github/workflows/tests.yml, libs.versions.toml
Jackson 2.15.x brings in a dependency that is not compatible with Java 8, and the shadowJar task fails. We will be stuck on Jackson 2.14.x until we move on from Java 8 support.
=> Redo 5.6.2 release

buildSrc/src/main/kotlin/ds3-java-sdk-library-convention.gradle.kts, libs.versions.toml
Look for a NIST NVD API key in the environment variable NVD_API_KEY and, if found, use it when running the OWASP dependency check tasks.
=> Allow for the use of a NIST NVD API key
